# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

jobs:
  build:
    working_directory: ~/wp-display-android

    docker:
      - image: circleci/android:api-28

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
         name: Init
         command: |
           chmod +x ./gradlew
           ./gradlew -version

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Assemble
          command: ./gradlew assembleDebug

      - run:
          name: Run Lint
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports/lint-results.html
