# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    working_directory: ~/wp-display-android

    docker:
      - image: circleci/android:api-30

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
         name: Init
         command: |
           chmod +x ./gradlew
           ./gradlew -version

      - run:
          name: Assemble
          command: ./gradlew assembleDebug

      - run:
          name: Run Lint
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports/lint-results.html

      - save_cache:
          key: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
