name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Info
        run: ./gradlew -version

      - name: Assemble Debug
        run: ./gradlew assembleDebug

      # To speed up lint check only run for release variant.
      - name: Lint Release
        run: ./gradlew :app:lintRelease

      - uses: actions/upload-artifact@v2
        if: ${{ always() }} # Also upload if lint errors.
        with:
          name: Lint reports
          path: |
            app/build/reports/lint-results-release.html
