name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    # Only run on pushes or if pull request from fork
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    permissions:
      checks: write # to publish unit test results

    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Info
        run: ./gradlew -version

      - name: Assemble Debug
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew :dtareader:test

      - name: Upload Unit Test Reports
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
        if: always() # also run if tests failed
        with:
          name: JUnit Report
          path: dtareader/build/test-results/**/*.xml
          reporter: java-junit

      # To speed up lint check only run for release variant.
      - name: Lint Release
        run: ./gradlew :app:lintRelease

      - name: Upload Lint Reports
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: ${{ always() }} # Also upload if lint errors.
        with:
          name: Lint reports
          path: |
            app/build/reports/lint-results-release.html
